# action.yml
name: 'GitHub Release to Issue'
branding:
  icon: 'bell'
  color: 'blue'
description: 'Monitors GitHub releases (using semver), and creates an issue in any other repo.'
inputs:
  repo:
    description: "Monitored repo, in the form org/repo (org may be a user)"
    required: True

  version:
    description: "Current version"
    required: True

  constraint:
    description: "An optional constraint, if you need to limit the releases considered. i.e. <4.0.0"
    required: False

  max_age:
    description: "How many days to consider on the feed. If you run this action on a schedule you probably want this to match."
    required: True

  labels:
    description: "Optional labels, comma separated"
    required: False

  token:
    description: "GitHub token"
    required: True
outputs:
  release_url:
    description: "Release API URL"
  issue_url: 
    description: "Created issue API URL"
runs:
  using: 'node12'
  main: 'index.js'
